"""Renamed password_hash to password in User model

Revision ID: 242542cf438b
Revises: eea9b1e56f83
Create Date: 2024-08-19 19:06:29.947460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242542cf438b'
down_revision = 'eea9b1e56f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.drop_index('ix_landlord_name')

    op.drop_table('landlord')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index('ix_tenant_name')

    op.drop_table('tenant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('property_address', sa.VARCHAR(length=120), nullable=True),
    sa.Column('landlord_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlord.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index('ix_tenant_name', ['name'], unique=False)

    op.create_table('landlord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('address', sa.VARCHAR(length=120), nullable=True),
    sa.Column('contract', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('landlord', schema=None) as batch_op:
        batch_op.create_index('ix_landlord_name', ['name'], unique=False)

    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
